### PR TITLE
Update Accessibility Considerations text

### PR DESCRIPTION
**Pull request by QingAn**
Related to #32

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/miniapp-lifecycle/pull/34.html" title="Last updated on Sep 19, 2022, 7:36 AM UTC (f14672d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/miniapp-lifecycle/34/85839ce...f14672d.html" title="Last updated on Sep 19, 2022, 7:36 AM UTC (f14672d)">Diff</a>

### CODE REVIEW

**Comment by pes10k** [comment]
Hello @xfq i think this is a good change! It would be good to add a bit more guidance to implementors on what (and how) they should consider and account for when considering accessibility issues

**Comment by QingAn** [comment]
> It would be good to add a bit more guidance to implementors on what (and how) they should consider and account for when considering accessibility issues

@pes10k @xfq I added some description accordingly. Please take a look.

**Comment by pes10k** [comment]
@QingAn i think this looks like a positive improvement, thank you!  I satisfies my concerns (I only filed it as a note when doing the privacy review), so feel free to close my issue if you'd like. However, as a suggestion, you might reach out to the W3C accessibility group for their thoughts too.

**Comment by QingAn** [comment]
> as a suggestion, you might reach out to the W3C accessibility group for their thoughts too.

Yes, I am also discussing with the team contact of accessibility group on this.

**Pull request merged**
